### PR TITLE
Feature of the one underscore in Numeric Literal on Java SE 1.7

### PR DESCRIPTION
**Pull request by loustler**
# 공유하고자 하는 지식 
 Java SE 1.7 feature 중 한 개 

# 내용을 요약하면 어떤 내용인 지?
 숫자 표현에 `_`(underscore)를 사용해서 가독성을 높게 작성할 수 있음

### CODE REVIEW

**Comment by loustler** [comment]
If you want further information? 

[Here](http://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html)

**Review by ghost — APPROVED** [review]
lgtm :+1:

**Comment by loustler** [comment]
@m-s-k Why you not merge to master?
It has some problem you think?
If so, let me know.

**Comment by loustler** [comment]
@m-s-k
I think this event was your mistake.
So i merged to master i think no more further comment.

**Comment by ghost** [comment]
@loustler 
thx!

**Pull request merged**
