### PR TITLE
Guarded Suspension Pattern

### PR DESCRIPTION
**Pull request by audtjddld**
# 공유하고자 하는 지식 
kind of  Multi Thread design Pattern
 Guarded Suspention Pattern
# 내용을 요약하면 어떤 내용인 지?
Guarded Suspension Pattern of Multi Thread design Pattern

### CODE REVIEW

**Comment by loustler** [comment]
Merged to master.

**Comment by loustler** [comment]
@audtjddld This topic is Java and Thread? Please set labels.

**Comment by audtjddld** [comment]
How do I set up labels? @loustler

**Comment by loustler** [comment]
It is possible when send your PRs. 

See category of labels on right your panel.

@audtjddld

**Comment by audtjddld** [comment]
Thanks @loustler

**Comment by loustler** [comment]
@audtjddld
Could you resend PRs? 
Cause your commit has unuseful file(`.project`).
Notify me if you resend PRs.
And then i'll merged to master.

**Comment by ghost** [comment]
Pretty good sequential diagram. Good job.

**Comment by loustler** [comment]
@audtjddld My request successfully completed. 
See #6

**Pull request merged**
